export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_RECENTLY_ADDED_PRODUCT = "GET_RECENTLY_ADDED_PRODUCT";
export const GET_PRODUCT_BY_CATEGRY = "GET_PRODUCT_BY_CATEGORY";
